# Generated by Django 4.2.21 on 2025-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedata',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10),
        ),
    ]
