# Generated by Django 4.2.21 on 2025-07-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_maintenancedata_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(help_text='room number (e.g., A-101)', max_length=50, unique=True)),
                ('owners', models.CharField(help_text='Owners of the room', max_length=255)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(help_text='Mode of payemnt', max_length=80)),
                ('parking', models.DecimalField(decimal_places=2, default=0.0, help_text='Parking charges', max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty charges (if any)', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10)),
            ],
            options={
                'verbose_name': 'Pay Log',
                'verbose_name_plural': 'Pay Logs',
                'ordering': ['room'],
            },
        ),
    ]
