# Generated by Django 4.2.21 on 2025-07-17 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_paylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paylog',
            options={'ordering': ['-payment_date', '-date_made'], 'verbose_name': 'Pay Log', 'verbose_name_plural': 'Pay Logs'},
        ),
        migrations.RemoveField(
            model_name='paylog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='paylog',
            name='total',
        ),
        migrations.AddField(
            model_name='paylog',
            name='date_made',
            field=models.DateField(default=datetime.date.today, help_text='Date of receipt'),
        ),
        migrations.AddField(
            model_name='paylog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description or notes for the payment', null=True),
        ),
        migrations.AddField(
            model_name='paylog',
            name='lease_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lease Rent at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paylog',
            name='months',
            field=models.CharField(default='', help_text='Number of months covered by this payment', max_length=100),
        ),
        migrations.AddField(
            model_name='paylog',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual amount paid by the member', max_digits=10),
        ),
        migrations.AddField(
            model_name='paylog',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, help_text='Date the payment was made'),
        ),
        migrations.AddField(
            model_name='paylog',
            name='period',
            field=models.CharField(default='', help_text='Specific period covered (e.g., AUG-SEP 2024)', max_length=255),
        ),
        migrations.AddField(
            model_name='paylog',
            name='periodic_building_maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='PBM at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paylog',
            name='repair_and_maintenance_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='RMF at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paylog',
            name='sinking_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking Funds at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paylog',
            name='space',
            field=models.CharField(default='', help_text='Space (e.g., 1BHK, 2BHK) (auto-filled from MaintenanceData)', max_length=50),
        ),
        migrations.AddField(
            model_name='paylog',
            name='total_maintenance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total maintenance amount due (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='owners',
            field=models.CharField(default='', help_text='Owners of the room (auto-filled from MaintenanceData)', max_length=255),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='parking',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Parking charges at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='payment_mode',
            field=models.CharField(default='', help_text='Mode of payment (e.g., CASH, UPI, CHEQUE)', max_length=50),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty at time of payment (auto-filled from MaintenanceData)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='room',
            field=models.CharField(default='', help_text='Room number for which payment is made', max_length=50),
        ),
    ]
