# Generated by Django 4.2.21 on 2025-07-19 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_alter_paylog_options_remove_paylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylog',
            name='cheque_draw_date',
            field=models.DateField(default=datetime.date.today, help_text='Cheque Draw date'),
        ),
        migrations.AddField(
            model_name='paylog',
            name='cheque_num',
            field=models.IntegerField(default=0, help_text='Cheque Number', max_length=6),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance pending or Advance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Any Notes', null=True),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='lease_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lease Rent', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='months',
            field=models.CharField(default='', help_text='Number of months covered', max_length=100),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='owners',
            field=models.CharField(default='', help_text='Owners', max_length=255),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='parking',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Parking charges', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='payment_mode',
            field=models.CharField(default='', help_text='Mode of payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='period',
            field=models.CharField(default='', help_text='Period covered (e.g., AUG-SEP 2024)', max_length=255),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='periodic_building_maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Periodic Building Maintenance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='repair_and_maintenance_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Repair and Maintenance Fund', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='room',
            field=models.CharField(default='', help_text='Room number', max_length=50),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='sinking_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking Funds', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='space',
            field=models.CharField(default='', help_text='Space (e.g., 1BHK, 2BHK)', max_length=50),
        ),
        migrations.AlterField(
            model_name='paylog',
            name='total_maintenance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total maintenance amount', max_digits=10),
        ),
    ]
