# Generated by Django 4.2.21 on 2025-07-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_paylog_cheque_draw_date_paylog_cheque_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylog',
            name='cheque_num',
            field=models.IntegerField(default=0, help_text='Cheque Number'),
        ),
    ]
