# Generated by Django 4.2.21 on 2025-07-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_alter_paylog_cheque_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paylog',
            old_name='room',
            new_name='room_no',
        ),
    ]
