# Generated by Django 4.2.21 on 2025-07-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_rename_room_paylog_room_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancedata',
            options={'ordering': ['id'], 'verbose_name': 'Maintenance Data Entry', 'verbose_name_plural': 'Maintenance Data Entries'},
        ),
    ]
