# Generated by Django 4.2.21 on 2025-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_alter_maintenancedata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacewiseCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(help_text='Space', max_length=10)),
                ('periodic_building_maintenance', models.DecimalField(decimal_places=2, default=0.0, help_text='Periodic building maintenance', max_digits=10)),
                ('repair_and_maintenance_fund', models.DecimalField(decimal_places=2, default=0.0, help_text='Repair and maintenance fund', max_digits=10)),
                ('sinking_funds', models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking funds', max_digits=10)),
                ('lease_rent', models.DecimalField(decimal_places=2, default=0.0, help_text='Lease rent', max_digits=10)),
            ],
            options={
                'verbose_name': 'Spacewise Maintenance Charges',
                'verbose_name_plural': 'Maintenance Data Entries',
                'ordering': ['id'],
            },
        ),
    ]
