# Generated by Django 4.2.21 on 2025-07-23 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_spacewisecharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylog',
            name='cheque_draw_date',
            field=models.DateField(default=datetime.date.today, help_text='Cheque Draw date', null=True),
        ),
    ]
