# Generated by Django 4.2.21 on 2025-07-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_alter_paylog_cheque_draw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylog',
            name='months',
            field=models.IntegerField(default='1', help_text='Number of months covered'),
        ),
    ]
