# Generated by Django 4.2.21 on 2025-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_alter_paylog_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacewisecharges',
            name='parking',
            field=models.JSONField(default=dict),
        ),
    ]
