# Generated by Django 4.2.21 on 2025-07-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_spacewisecharges_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedata',
            name='lease_rent',
        ),
        migrations.RemoveField(
            model_name='maintenancedata',
            name='periodic_building_maintenance',
        ),
        migrations.RemoveField(
            model_name='maintenancedata',
            name='repair_and_maintenance_fund',
        ),
        migrations.RemoveField(
            model_name='maintenancedata',
            name='sinking_funds',
        ),
        migrations.AddField(
            model_name='maintenancedata',
            name='charges',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='charge', to='core_api.spacewisecharges'),
        ),
    ]
