# Generated by Django 4.2.21 on 2025-07-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_remove_maintenancedata_lease_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedata',
            name='charges',
        ),
        migrations.AddField(
            model_name='maintenancedata',
            name='lease_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lease rent', max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedata',
            name='periodic_building_maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Periodic building maintenance', max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedata',
            name='repair_and_maintenance_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Repair and maintenance fund', max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedata',
            name='sinking_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking funds', max_digits=10),
        ),
        migrations.CreateModel(
            name='MaintenanceDataNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(help_text='room number (e.g., A-101)', max_length=50, unique=True)),
                ('owners', models.CharField(help_text='Owners of the room', max_length=255)),
                ('space', models.CharField(help_text='Space', max_length=10)),
                ('parking', models.DecimalField(decimal_places=2, default=0.0, help_text='Parking charges', max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty charges (if any)', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10)),
                ('charges', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='charge', to='core_api.spacewisecharges')),
            ],
            options={
                'verbose_name': 'Maintenance Data Entry',
                'verbose_name_plural': 'Maintenance Data Entries',
                'ordering': ['id'],
            },
        ),
    ]
