# Generated by Django 4.2.21 on 2025-07-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_remove_maintenancedata_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge', to='core_api.spacewisecharges'),
        ),
    ]
