# Generated by Django 4.2.21 on 2025-07-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0016_alter_maintenancedatanew_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedatanew',
            name='charges',
        ),
    ]
