# Generated by Django 4.2.21 on 2025-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0017_remove_maintenancedatanew_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDataRe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(help_text='room number (e.g., A-101)', max_length=50, unique=True)),
                ('owners', models.CharField(help_text='Owners of the room', max_length=255)),
                ('space', models.CharField(help_text='Space', max_length=10)),
                ('periodic_building_maintenance', models.DecimalField(decimal_places=2, default=0.0, help_text='Periodic building maintenance', max_digits=10)),
                ('repair_and_maintenance_fund', models.DecimalField(decimal_places=2, default=0.0, help_text='Repair and maintenance fund', max_digits=10)),
                ('sinking_funds', models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking funds', max_digits=10)),
                ('parking', models.DecimalField(decimal_places=2, default=0.0, help_text='Parking charges', max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty charges (if any)', max_digits=10)),
                ('lease_rent', models.DecimalField(decimal_places=2, default=0.0, help_text='Lease rent', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='balance', max_digits=10)),
            ],
            options={
                'verbose_name': 'Maintenance Data Entry',
                'verbose_name_plural': 'Maintenance Data Entries',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MaintenanceData',
        ),
    ]
