# Generated by Django 4.2.21 on 2025-07-24 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0018_maintenancedatare_delete_maintenancedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLogRe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(default='', help_text='Room number', max_length=50)),
                ('owners', models.CharField(default='', help_text='Owners', max_length=255)),
                ('date_made', models.DateField(default=datetime.date.today, help_text='Date of receipt')),
                ('months', models.IntegerField(default=1, help_text='Number of months covered')),
                ('period', models.CharField(default='', help_text='Period covered (e.g., AUG-SEP 2024)', max_length=255)),
                ('space', models.CharField(default='', help_text='Space (e.g., 1BHK, 2BHK)', max_length=50)),
                ('periodic_building_maintenance', models.DecimalField(decimal_places=2, default=0.0, help_text='Periodic Building Maintenance', max_digits=10)),
                ('repair_and_maintenance_fund', models.DecimalField(decimal_places=2, default=0.0, help_text='Repair and Maintenance Fund', max_digits=10)),
                ('sinking_funds', models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking Funds', max_digits=10)),
                ('parking', models.DecimalField(decimal_places=2, default=0.0, help_text='Parking charges', max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty', max_digits=10)),
                ('lease_rent', models.DecimalField(decimal_places=2, default=0.0, help_text='Lease Rent', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance pending or Advance', max_digits=10)),
                ('total_maintenance_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total maintenance amount', max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid', max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today, help_text='Date the payment was made')),
                ('payment_mode', models.CharField(default='', help_text='Mode of payment', max_length=50)),
                ('cheque_num', models.IntegerField(default=0, help_text='Cheque Number')),
                ('cheque_draw_date', models.DateField(default=datetime.date.today, help_text='Cheque Draw date', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Any Notes', null=True)),
            ],
            options={
                'verbose_name': 'Pay Log',
                'verbose_name_plural': 'Pay Logs',
                'ordering': ['-payment_date', '-date_made'],
            },
        ),
        migrations.DeleteModel(
            name='PayLog',
        ),
        migrations.AlterModelOptions(
            name='maintenancedatanew',
            options={'ordering': ['id'], 'verbose_name': 'Room Maintenance Entry', 'verbose_name_plural': 'Room Maintenance Entries'},
        ),
        migrations.RenameField(
            model_name='spacewisecharges',
            old_name='space',
            new_name='space_type',
        ),
        migrations.RemoveField(
            model_name='maintenancedatanew',
            name='space',
        ),
        migrations.RemoveField(
            model_name='spacewisecharges',
            name='parking',
        ),
        migrations.AddField(
            model_name='maintenancedatanew',
            name='lease_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedatanew',
            name='periodic_building_maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedatanew',
            name='repair_and_maintenance_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedatanew',
            name='sinking_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancedatanew',
            name='space_type',
            field=models.ForeignKey(blank=True, help_text='Select the space type to auto-fill charges', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to='core_api.spacewisecharges'),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Room-specific outstanding balance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='parking',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Room-specific penalty charges (if any)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='room',
            field=models.CharField(help_text='Unique room number (e.g., A-101)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated total amount for this room', max_digits=10),
        ),
    ]
