# Generated by Django 4.2.21 on 2025-07-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0019_paylogre_delete_paylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedatanew',
            name='apply_lease_rent',
            field=models.BooleanField(default=False, help_text='Apply lease rent for this room?'),
        ),
        migrations.AddField(
            model_name='maintenancedatanew',
            name='num_vehicles',
            field=models.IntegerField(default=0, help_text='Number of vehicles(0 for no parking)'),
        ),
        migrations.AddField(
            model_name='spacewisecharges',
            name='parking',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='lease_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lease rent Charge', max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='periodic_building_maintenance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Periodic building maintenance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='repair_and_maintenance_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Repair and maintenance fund', max_digits=10),
        ),
        migrations.AlterField(
            model_name='maintenancedatanew',
            name='sinking_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sinking funds', max_digits=10),
        ),
    ]
