# Generated by Django 4.2.21 on 2025-08-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0020_maintenancedatanew_apply_lease_rent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancedatanew',
            old_name='num_vehicles',
            new_name='num_of_vehicles',
        ),
    ]
