# Generated by Django 4.2.21 on 2025-08-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0021_rename_num_vehicles_maintenancedatanew_num_of_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacewisecharges',
            options={'ordering': ['id'], 'verbose_name': 'Spacewise Maintenance Charges', 'verbose_name_plural': 'Spacewise Maintenance Charges'},
        ),
    ]
