# Generated by Django 4.2.21 on 2025-08-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0022_alter_spacewisecharges_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylogre',
            name='period',
            field=models.TextField(default='', help_text='Period covered (e.g., AUG-SEP 2024)', max_length=255),
        ),
    ]
