# Generated by Django 4.2.21 on 2025-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0023_alter_paylogre_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedatanew',
            name='space_type_val',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
