# Generated by Django 4.2.21 on 2025-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0024_maintenancedatanew_space_type_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacewisecharges',
            name='additional_charges',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='spacewisecharges',
            name='lease_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lease/rent', max_digits=10),
        ),
    ]
