# Generated by Django 4.2.21 on 2025-09-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0025_spacewisecharges_additional_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedatanew',
            name='additional_charges',
            field=models.JSONField(default=dict),
        ),
    ]
